import fs from 'node:fs/promises';import {createRequire} from 'node:module';
const require=createRequire('C:/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/runtime.cjs');const {chromium}=require('playwright');const browser=await chromium.launch({headless:true,channel:'chrome'});
const root='opendesign/review/archbuddy-showcase-scroll-reveal',base=process.env.REVEAL_PUBLIC_URL||'http://127.0.0.1:8766/mockups/archbuddy-showcase/',kind=process.env.REVEAL_PUBLIC_URL?'public':'local';const pause=ms=>new Promise(r=>setTimeout(r,ms));const report={generated:new Date().toISOString(),scope:kind,cases:[],errors:[]};
const absolute=e=>{let y=0;while(e){y+=e.offsetTop;e=e.offsetParent;}return y;};
try{for(const width of [1440,390]){const context=await browser.newContext({viewport:{width,height:width===1440?1000:844}}),page=await context.newPage();const pageErrors=[],consoleErrors=[],documents=[];page.on('response',res=>{if(res.request().resourceType()==='document')documents.push({url:res.url(),status:res.status(),type:res.headers()['content-type'],attachment:res.headers()['content-disposition']||null});});page.on('pageerror',e=>pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});const response=await page.goto(base,{waitUntil:'load'});await pause(200);
const c={width,initialHttp:response.status(),pageErrors,consoleErrors,chapters:[]};report.cases.push(c);
if(kind==='public'&&await page.getByRole('button',{name:/确定访问/}).count()){c.platformWarning=true;await pause(3200);await page.getByText('确定访问',{exact:true}).click();await page.waitForLoadState('load');await pause(250);c.platformConsoleErrors=[...consoleErrors];consoleErrors.length=0;}
c.documents=documents;c.entry=await page.evaluate(()=>({url:location.href,motion:document.body.dataset.motion,parts:document.querySelectorAll('.motion-part').length,headings:document.querySelectorAll('.motion-heading').length,stages:document.querySelectorAll('.motion-stage').length,comparisonControls:document.querySelectorAll('.motion-controls,[data-motion-option]').length,cache:[...document.querySelectorAll('link[rel="stylesheet"],script[src]')].map(e=>e.href||e.src),width:document.documentElement.scrollWidth,initial:[...document.querySelectorAll('.motion-part')].map(e=>({opacity:getComputedStyle(e).opacity,revealed:e.classList.contains('is-revealed')}))}));
c.alignment=await page.evaluate(()=>({imageRight:document.querySelector('.hero-visual').getBoundingClientRect().right,downloadRight:document.querySelector('.header-download').getBoundingClientRect().right}));
if(c.entry.parts!==10||c.entry.motion!=='reveal')throw new Error('初始化未完成 '+JSON.stringify(c.entry));
if(width===1440)await page.screenshot({path:root+'/'+kind+'-1440-hero.png'});
for(let i=0;i<5;i++){const h=page.locator('.motion-heading').nth(i),s=page.locator('.motion-stage').nth(i);const top=await h.evaluate(absolute),vh=await page.evaluate(()=>innerHeight),current=await page.evaluate(()=>scrollY);await page.mouse.move(width-40,400);await page.mouse.wheel(0,top-vh*.85-current);await pause(35);const first=await h.evaluate(e=>({opacity:getComputedStyle(e).opacity,revealed:e.classList.contains('is-revealed')}));await pause(850);const st=await s.evaluate(absolute),now=await page.evaluate(()=>scrollY);await page.mouse.wheel(0,Math.max(100,st-vh*.72-now));await pause(35);const stageStart=await s.evaluate(e=>({opacity:getComputedStyle(e).opacity,revealed:e.classList.contains('is-revealed')}));await pause(850);const settled=await page.evaluate(i=>{const h=document.querySelectorAll('.motion-heading')[i],s=document.querySelectorAll('.motion-stage')[i];return{headingText:h.textContent.trim(),headingOpacity:getComputedStyle(h).opacity,stageOpacity:getComputedStyle(s).opacity,headingPosition:getComputedStyle(h).position,stageTransform:getComputedStyle(s).transform,revealed:h.classList.contains('is-revealed')&&s.classList.contains('is-revealed'),width:document.documentElement.scrollWidth,textLength:s.textContent.trim().length,height:s.getBoundingClientRect().height};},i);c.chapters.push({index:i+1,first,stageStart,settled});if((width===1440&&[0,1].includes(i))||(width===390&&i===3))await page.screenshot({path:root+'/'+kind+'-'+width+'-chapter-'+(i+1)+'.png'});}
await page.mouse.wheel(0,-20000);await pause(700);c.backscroll=await page.evaluate(()=>[...document.querySelectorAll('.motion-part')].map(e=>({revealed:e.classList.contains('is-revealed'),opacity:getComputedStyle(e).opacity})));
await page.locator('.site-header a[href="#features"]').click();await pause(900);c.nav=await page.evaluate(()=>({hash:location.hash,titleTop:document.getElementById('features-title').getBoundingClientRect().top,headerBottom:document.querySelector('.site-header').getBoundingClientRect().bottom}));
await page.locator('[data-gallery="prompt"] [data-variant="1"]').click();c.promptVariant=await page.locator('#prompt-image').getAttribute('src');await page.locator('[data-gallery="prompt"] [data-variant="0"]').click();await page.locator('[data-gallery="assets"] [data-variant="1"]').click();c.assetVariant=await page.locator('#assets-image').getAttribute('src');await page.locator('[data-gallery="assets"] [data-variant="0"]').click();
await page.locator('.brand').click();await pause(900);await page.locator('[data-enlarge="hero-image"]').click();c.dialogOpen=await page.locator('#image-dialog').evaluate(e=>e.open);await page.locator('[data-close-dialog]').click();c.dialogClosed=await page.locator('#image-dialog').evaluate(e=>!e.open);
c.links=await page.evaluate(()=>({chrome:[...document.querySelectorAll('a.button')].filter(e=>e.textContent.includes('Chrome')).map(e=>({text:e.textContent.trim(),href:e.href,download:e.hasAttribute('download')})),testset:[...document.querySelectorAll('a.button')].filter(e=>e.textContent.includes('测试集')).map(e=>({text:e.textContent.trim(),href:e.href,download:e.getAttribute('download')})),steps:[...document.querySelectorAll('.install-steps h3')].map(e=>e.textContent.trim()),finalWidth:document.documentElement.scrollWidth}));
await context.close();}}
catch(e){report.errors.push(String(e));}finally{await browser.close();await fs.writeFile(root+'/'+kind+'-check-summary.json',JSON.stringify(report,null,2));}console.log(JSON.stringify({scope:kind,cases:report.cases.length,errors:report.errors,pageErrors:report.cases.flatMap(c=>c.pageErrors),consoleErrors:report.cases.flatMap(c=>c.consoleErrors),settled:report.cases.map(c=>({width:c.width,parts:c.entry?.parts,alignment:c.alignment,chapters:c.chapters.map(x=>({n:x.index,opacity:x.settled.stageOpacity,position:x.settled.headingPosition,transform:x.settled.stageTransform}))}))},null,2));
